[package]
name = "communication"
version = "0.2.0"
authors = ["学少何 <a664554724@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
lazy_static = "1.4.0"